package com.rejowan.ccpc

enum class Country (val countryIso: String, val countryName: String, val countryCode: String) {
    Andorra("AD", "Andorra", "+376"),
    UnitedArabEmirates("AE", "United Arab Emirates", "+971"),
    Afghanistan("AF", "Afghanistan", "+93"),
    AntiguaAndBarbuda("AG", "Antigua and Barbuda", "+1"),
    Anguilla("AI", "Anguilla", "+1"),
    Albania("AL", "Albania", "+355"),
    Armenia("AM", "Armenia", "+374"),
    Angola("AO", "Angola", "+244"),
    Antarctica("AQ", "Antarctica", "+672"),
    Argentina("AR", "Argentina", "+54"),
    AmericanSamoa("AS", "American Samoa", "+1"),
    Austria("AT", "Austria", "+43"),
    Australia("AU", "Australia", "+61"),
    Aruba("AW", "Aruba", "+297"),
    AlandIslands("AX", "Aland Islands", "+358"),
    Azerbaijan("AZ", "Azerbaijan", "+994"),
    BosniaAndHerzegovina("BA", "Bosnia and Herzegovina", "+387"),
    Barbados("BB", "Barbados", "+1"),
    Bangladesh("BD", "Bangladesh", "+880"),
    Belgium("BE", "Belgium", "+32"),
    BurkinaFaso("BF", "Burkina Faso", "+226"),
    Bulgaria("BG", "Bulgaria", "+359"),
    Bahrain("BH", "Bahrain", "+973"),
    Burundi("BI", "Burundi", "+257"),
    Benin("BJ", "Benin", "+229"),
    SaintBarthelemy("BL", "Saint Barthélemy", "+590"),
    Bermuda("BM", "Bermuda", "+1"),
    BruneiDarussalam("BN", "Brunei Darussalam", "+673"),
    Bolivia("BO", "Bolivia", "+591"),
    Brazil("BR", "Brazil", "+55"),
    Bahamas("BS", "Bahamas", "+1"),
    Bhutan("BT", "Bhutan", "+975"),
    Botswana("BW", "Botswana", "+267"),
    Belarus("BY", "Belarus", "+375"),
    Belize("BZ", "Belize", "+501"),
    Canada("CA", "Canada", "+1"),
    CocosKeelingIslands("CC", "Cocos (Keeling) Islands", "+61"),
    CongoKinshasaDRC("CD", "Democratic Republic Of The Congo", "+243"),
    CentralAfricanRepublic("CF", "Central African Republic", "+236"),
    CongoBrazzavilleRepublic("CG", "Congo Republic", "+242"),
    Switzerland("CH", "Switzerland", "+41"),
    CoteDivoire("CI", "Côte D'Ivoire", "+225"),
    CookIslands("CK", "Cook Islands", "+682"),
    Chile("CL", "Chile", "+56"),
    Cameroon("CM", "Cameroon", "+237"),
    China("CN", "China", "+86"),
    Colombia("CO", "Colombia", "+57"),
    CostaRica("CR", "Costa Rica", "+506"),
    Cuba("CU", "Cuba", "+53"),
    CapeVerde("CV", "Cape Verde", "+238"),
    Curacao("CW", "Curaçao", "+599"),
    Christmas("CX", "Christmas Island", "+61"),
    CyprusIsland("CY", "Cyprus", "+357"),
    CzechRepublic("CZ", "Czech Republic", "+420"),
    Germany("DE", "Germany", "+49"),
    Djibouti("DJ", "Djibouti", "+253"),
    Denmark("DK", "Denmark", "+45"),
    Dominica("DM", "Dominica", "+1"),
    DominicanRepublic("DO", "Dominican Republic", "+1"),
    Algeria("DZ", "Algeria", "+213"),
    Ecuador("EC", "Ecuador", "+593"),
    Estonia("EE", "Estonia", "+372"),
    Egypt("EG", "Egypt", "+20"),
    Eritrea("ER", "Eritrea", "+291"),
    Spain("ES", "Spain", "+34"),
    Ethiopia("ET", "Ethiopia", "+251"),
    Finland("FI", "Finland", "+358"),
    Fiji("FJ", "Fiji", "+679"),
    FalklandIslands("FK", "Falkland Islands (Malvinas)", "+500"),
    Micronesia("FM", "Micronesia", "+691"),
    FaroeIslands("FO", "Faroe Islands", "+298"),
    France("FR", "France", "+33"),
    Gabon("GA", "Gabon", "+241"),
    UnitedKingdom("GB", "United Kingdom", "+44"),
    Grenada("GD", "Grenada", "+1"),
    Georgia("GE", "Georgia", "+995"),
    FrenchGuyana("GF", "French Guyana", "+594"),
    Ghana("GH", "Ghana", "+233"),
    Gibraltar("GI", "Gibraltar", "+350"),
    Greenland("GL", "Greenland", "+299"),
    Gambia("GM", "Gambia", "+220"),
    Guinea("GN", "Guinea", "+224"),
    Guadeloupe("GP", "Guadeloupe", "+590"),
    EquatorialGuinea("GQ", "Equatorial Guinea", "+240"),
    Greece("GR", "Greece", "+30"),
    Guatemala("GT", "Guatemala", "+502"),
    Guam("GU", "Guam", "+1"),
    GuineaBissau("GW", "Guinea-bissau", "+245"),
    Guyana("GY", "Guyana", "+592"),
    HongKong("HK", "Hong Kong", "+852"),
    Honduras("HN", "Honduras", "+504"),
    Croatia("HR", "Croatia", "+385"),
    Haiti("HT", "Haiti", "+509"),
    Hungary("HU", "Hungary", "+36"),
    Indonesia("ID", "Indonesia", "+62"),
    Ireland("IE", "Ireland", "+353"),
    Israel("IL", "Israel", "+972"),
    IsleOfMan("IM", "Isle Of Man", "+44"),
    India("IN", "India", "+91"),
    BritishIndianOceanTerritory("IO", "British Indian Ocean Territory", "+246"),
    Iraq("IQ", "Iraq", "+964"),
    Iran("IR", "Iran, Islamic Republic Of", "+98"),
    Iceland("IS", "Iceland", "+354"),
    Italy("IT", "Italy", "+39"),
    Jersey("JE", "Jersey", "+44"),
    Jamaica("JM", "Jamaica", "+1"),
    Jordan("JO", "Jordan", "+962"),
    Japan("JP", "Japan", "+81"),
    Kenya("KE", "Kenya", "+254"),
    Kyrgyzstan("KG", "Kyrgyzstan", "+996"),
    Cambodia("KH", "Cambodia", "+855"),
    Kiribati("KI", "Kiribati", "+686"),
    Comoros("KM", "Comoros", "+269"),
    SaintKittsAndNevis("KN", "Saint Kitts And Nevis", "+1"),
    NorthKorea("KP", "North Korea", "+850"),
    SouthKorea("KR", "South Korea", "+82"),
    Kuwait("KW", "Kuwait", "+965"),
    CaymanIslands("KY", "Cayman Islands", "+1"),
    Kazakhstan("KZ", "Kazakhstan", "+7"),
    Lao("LA", "Lao People's Democratic Republic", "+856"),
    Lebanon("LB", "Lebanon", "+961"),
    SaintLucia("LC", "Saint Lucia", "+1"),
    Liechtenstein("LI", "Liechtenstein", "+423"),
    SriLanka("LK", "Sri Lanka", "+94"),
    Liberia("LR", "Liberia", "+231"),
    Lesotho("LS", "Lesotho", "+266"),
    Lithuania("LT", "Lithuania", "+370"),
    Luxembourg("LU", "Luxembourg", "+352"),
    Latvia("LV", "Latvia", "+371"),
    Libya("LY", "Libya", "+218"),
    Morocco("MA", "Morocco", "+212"),
    Monaco("MC", "Monaco", "+377"),
    Moldova("MD", "Moldova, Republic Of", "+373"),
    Montenegro("ME", "Montenegro", "+382"),
    SaintMartin("MF", "Saint Martin", "+590"),
    Madagascar("MG", "Madagascar", "+261"),
    MarshallIslands("MH", "Marshall Islands", "+692"),
    NorthMacedonia("MK", "North Macedonia", "+389"),
    Mali("ML", "Mali", "+223"),
    Myanmar("MM", "Myanmar", "+95"),
    Mongolia("MN", "Mongolia", "+976"),
    Macau("MO", "Macau", "+853"),
    NorthernMarianaIslands("MP", "Northern Mariana Islands", "+1"),
    Martinique("MQ", "Martinique", "+596"),
    Mauritania("MR", "Mauritania", "+222"),
    Montserrat("MS", "Montserrat", "+1"),
    Malta("MT", "Malta", "+356"),
    Mauritius("MU", "Mauritius", "+230"),
    Maldives("MV", "Maldives", "+960"),
    Malawi("MW", "Malawi", "+265"),
    Mexico("MX", "Mexico", "+52"),
    Malaysia("MY", "Malaysia", "+60"),
    Mozambique("MZ", "Mozambique", "+258"),
    Namibia("NA", "Namibia", "+264"),
    NewCaledonia("NC", "New Caledonia", "+687"),
    Niger("NE", "Niger", "+227"),
    NorfolkIslands("NF", "Norfolk Islands", "+672"),
    Nigeria("NG", "Nigeria", "+234"),
    Nicaragua("NI", "Nicaragua", "+505"),
    Netherlands("NL", "Netherlands", "+31"),
    Norway("NO", "Norway", "+47"),
    Nepal("NP", "Nepal", "+977"),
    Nauru("NR", "Nauru", "+674"),
    Niue("NU", "Niue", "+683"),
    NewZealand("NZ", "New Zealand", "+64"),
    Oman("OM", "Oman", "+968"),
    Panama("PA", "Panama", "+507"),
    Peru("PE", "Peru", "+51"),
    FrenchPolynesia("PF", "French Polynesia", "+689"),
    PapuaNewGuinea("PG", "Papua New Guinea", "+675"),
    Philippines("PH", "Philippines", "+63"),
    Pakistan("PK", "Pakistan", "+92"),
    Poland("PL", "Poland", "+48"),
    SaintPierreAndMiquelon("PM", "Saint Pierre And Miquelon", "+508"),
    PitcairnIslands("PN", "Pitcairn Islands", "+870"),
    PuertoRico("PR", "Puerto Rico", "+1"),
    Palestine("PS", "Palestine", "+970"),
    Portugal("PT", "Portugal", "+351"),
    Palau("PW", "Palau", "+680"),
    Paraguay("PY", "Paraguay", "+595"),
    Qatar("QA", "Qatar", "+974"),
    Reunion("RE", "Réunion", "+262"),
    Romania("RO", "Romania", "+40"),
    Serbia("RS", "Serbia", "+381"),
    RussianFederation("RU", "Russian Federation", "+7"),
    Rwanda("RW", "Rwanda", "+250"),
    SaudiArabia("SA", "Saudi Arabia", "+966"),
    SolomonIslands("SB", "Solomon Islands", "+677"),
    Seychelles("SC", "Seychelles", "+248"),
    Sudan("SD", "Sudan", "+249"),
    Sweden("SE", "Sweden", "+46"),
    Singapore("SG", "Singapore", "+65"),
    SaintHelena("SH", "Saint Helena, Ascension And Tristan Da Cunha", "+290"),
    Slovenia("SI", "Slovenia", "+386"),
    Slovakia("SK", "Slovakia", "+421"),
    SierraLeone("SL", "Sierra Leone", "+232"),
    SanMarino("SM", "San Marino", "+378"),
    Senegal("SN", "Senegal", "+221"),
    Somalia("SO", "Somalia", "+252"),
    Suriname("SR", "Suriname", "+597"),
    SouthSudan("SS", "South Sudan", "+211"),
    SaoTomeAndPrincipe("ST", "Sao Tome And Principe", "+239"),
    ElSalvador("SV", "El Salvador", "+503"),
    SintMaarten("SX", "Sint Maarten", "+1"),
    Syria("SY", "Syrian Arab Republic", "+963"),
    Swaziland("SZ", "Swaziland", "+268"),
    TurksAndCaicosIslands("TC", "Turks And Caicos Islands", "+1"),
    Chad("TD", "Chad", "+235"),
    Togo("TG", "Togo", "+228"),
    Thailand("TH", "Thailand", "+66"),
    Tajikistan("TJ", "Tajikistan", "+992"),
    Tokelau("TK", "Tokelau", "+690"),
    TimorLeste("TL", "Timor-leste", "+670"),
    Turkmenistan("TM", "Turkmenistan", "+993"),
    Tunisia("TN", "Tunisia", "+216"),
    Tonga("TO", "Tonga", "+676"),
    Turkey("TR", "Türkiye", "+90"),
    TrinidadAndTobago("TT", "Trinidad & Tobago", "+1"),
    Tuvalu("TV", "Tuvalu", "+688"),
    Taiwan("TW", "Taiwan", "+886"),
    Tanzania("TZ", "Tanzania, United Republic Of", "+255"),
    Ukraine("UA", "Ukraine", "+380"),
    Uganda("UG", "Uganda", "+256"),
    UnitedStates("US", "United States Of America", "+1"),
    Uruguay("UY", "Uruguay", "+598"),
    Uzbekistan("UZ", "Uzbekistan", "+998"),
    VaticanCity("VA", "Vatican City", "+379"),
    SaintVincentAndTheGrenadines("VC", "Saint Vincent & The Grenadines", "+1"),
    Venezuela("VE", "Venezuela, Bolivarian Republic Of", "+58"),
    BritishVirginIslands("VG", "British Virgin Islands", "+1"),
    USVirginIslands("VI", "US Virgin Islands", "+1"),
    Vietnam("VN", "Vietnam", "+84"),
    Vanuatu("VU", "Vanuatu", "+678"),
    WallisAndFutuna("WF", "Wallis And Futuna", "+681"),
    Samoa("WS", "Samoa", "+685"),
    Kosovo("XK", "Kosovo", "+383"),
    Yemen("YE", "Yemen", "+967"),
    Mayotte("YT", "Mayotte", "+262"),
    SouthAfrica("ZA", "South Africa", "+27"),
    Zambia("ZM", "Zambia", "+260"),
    Zimbabwe("ZW", "Zimbabwe", "+263");

    companion object{


        /**
         * Get all countries
         * @return List<Countries>
         */
        fun getAllCountries(): List<Country> {
            return entries.sortedBy { it.countryName }
        }

        /**
         * Get selected countries
         * @param selectedCountries List<Countries>
         * @return List<Countries>
         */
        fun getSelectedCountries(selectedCountries: List<Country>): List<Country> {
            return selectedCountries
        }

        /**
         * Get all countries except selected countries
         * @param selectedCountries List<Countries>
         * @return List<Countries>
         */
        fun getAllCountriesExcept(selectedCountries: List<Country>): List<Country> {
            return entries.filter { it !in selectedCountries }
        }


        /**
         * Search country by query
         * @param query String
         * @param list List<Countries>
         * @return List<Countries>
         */
        fun searchCountry(query: String, list: List<Country>): List<Country> {
            val normalizedQuery = query.trim()
            return list.filter { country ->
                country.countryIso.contains(normalizedQuery, true) ||
                        country.countryName.contains(normalizedQuery, true) ||
                        country.countryCode.contains(normalizedQuery, true)
            }
        }


    }


}